let productos = [
    {
        id: 0,
        nombre: "Fancy Mouse - Café Intenso",
        categoria: "café",
        precio: 22.95,
        cantidad: "280g",
        descripcion: "Potente pero sin amargarte la vida — nuestro espresso orgánico está hecho para que tomes el shot perfecto cada vez. Con toques de chocolate oscuro y nueces tostadas, queda buenísimo tanto solo como con leche.",
        sabor: "Maní, chocolate y caramelo",
        origen: "Peru, Sumatra",
        intensidad: "Intenso",
        fecha: "2024-07-01",
        imagen: "img/granos-de-cafe/fancymouse-dark.png",
        imagenes: [
            "img/granos-de-cafe/fancymouse-dark.png",
            "img/granos-de-cafe/fancymouse-dark-2.png",
            "img/granos-de-cafe/fancymouse-dark-3.png"
        ]
    },
    {
        id: 1,
        nombre: "Careless Cat - Café Equilibrado",
        categoria: "café",
        precio: 22.95,
        cantidad: "280g",
        descripcion: "Mitad de cafeína, el doble de estilo — Careless Cat es para cuando querés mantenerte despierta sin sentir que te explota la cabeza. Suave y con onda, trae notas de almendras tostadas, chocolate y caramelo. Perfecto para relajarte sin perder el ritmo..",
        sabor: "Almendras, chocolate y caramelo",
        origen: "México, Perú",
        intensidad: "Equilibrado",
        fecha: "2024-07-01",
        imagen: "img/granos-de-cafe/carelesscat-medium.png",
        imagenes: [
           "img/granos-de-cafe/carelesscat-medium.png",
            "img/granos-de-cafe/carelesscat-medium-2.png",
            "img/granos-de-cafe/carelesscat-medium-3.png",
        ]
    },
    {
        id: 2,
        nombre: "Vainilla Blend - Café Equilibrado",
        categoria: "café",
        precio: 19.95,
        cantidad: "280g",
        descripcion: "Brillante, suave y con mucha personalidad — nuestro blend orgánico de tueste ligero está hecho para mañanas tranqui y sabores limpios que se disfrutan fácil. Con un toque cítrico y un final suave, es una forma fresca de encarar tu café de todos los días.",
        sabor: "Madagascar Vanilla",
        origen: "Nicaragua",
        intensidad: "Equilibrado",
        fecha: "2024-07-01",
        imagen: "img/granos-de-cafe/vainillablend-medium.png",
        imagenes: [
            "img/granos-de-cafe/vainillablend-medium.png",
            "img/granos-de-cafe/vainillablend-medium-2.png",
            "img/granos-de-cafe/vainillablend-medium-3.png",
        ]
    },
    {
        id: 3,
        nombre: "Social Dog - Café Equilibrado",
        categoria: "café",
        precio: 19.95,
        cantidad: "280g",
        descripcion: "Equilibrado, suave y fácil de tomar sin pensarlo — nuestro blend orgánico de tueste medio es ese café comodín para los momentos de todos los días. Con notas acogedoras de chocolate con leche y maní tostado, es amigable, accesible y... imposible no quererlo.",
        sabor: "Chocolate, maní y galletitas.",
        origen: "Perú, Nicaragua",
        intensidad: "Equilibrado",
        fecha: "2025-09-27",
        imagen: "img/granos-de-cafe/socialdog-medium.png",
        imagenes: [
            "img/granos-de-cafe/socialdog-medium.png",
            "img/granos-de-cafe/socialdog-medium-2.png",
            "img/granos-de-cafe/socialdog-medium-3.png",
        ]
    },
    {
        id: 4,
        nombre: "Sleepy Sloth - Café Decaf Equilibrado ",
        categoria: "café",
        precio: 23.95,
        cantidad: "280g",
        descripcion: "Este descafeinado es para quienes quieren el sabor del café… sin el acelere. Perfecto para antes de dormir, sin arruinar tu rutina de sueño. Con un toque de sabor a fruta, ahora podés tomar café todo el día sin culpa — literalmente.",
        sabor: "Fruta caramelizada",
        origen: "Nicaragua",
        intensidad: "Equilibrado",
        fecha: "2025-09-27",
        imagen: "img/granos-de-cafe/sleepysloth-medium.png",
        imagenes: [
            "img/granos-de-cafe/sleepysloth-medium.png",
            "img/granos-de-cafe/sleepysloth-medium-2.png",
            "img/granos-de-cafe/sleepysloth-medium-3.png",
        ]
    },
    {
        id: 5,
        nombre: "Early Bird - Café Ligero",
        categoria: "café",
        precio: 19.95,
        cantidad: "280g",
        descripcion: "Brillante, suave y con mucha personalidad — nuestro blend orgánico de tueste ligero está hecho para mañanas tranqui y sabores limpios que se disfrutan fácil. Con un toque cítrico y un final suave, es una forma fresca de encarar tu café de todos los días.",
        sabor: "Manzana verde y chocolate con leche",
        origen: "Américas",
        intensidad: "Ligero",
        fecha: "2025-09-27",
        imagen: "img/granos-de-cafe/earlybird-light.png",
        imagenes: [
            "img/granos-de-cafe/earlybird-light.png",
            "img/granos-de-cafe/earlybird-light-2.png",
            "img/granos-de-cafe/earlybird-light-3.png",
        ]
    },
    {
        id: 6,
        nombre: "Variados Cold Brew",
        categoria: "cold brew",
        precio: 19.95,
        cantidad: "10 sobres",
        descripcion: "Probá todo el universo de Chamberlain Coffee con esta selección de nuestros blends más queridos, en un formato individual súper práctico. Desde los más intensos y audaces hasta los suaves y equilibrados, cada taza está pensada para que tengas calidad y comodidad en cada sorbo — perfecta tanto caliente como con hielo.",
        sabor: "Variado",
        origen: "Arabica",
        intensidad: "Ligero, Equilibrado, Intenso",
        fecha: "2024-07-01",
        imagen: "img/cafe-frio/variety.png",
        imagenes: [
            "img/cafe-frio/variety.png",
            "img/cafe-frio/variety-2.png",
            "img/cafe-frio/variety-3.png",
        ]
    },
    {
        id: 7,
        nombre: "Vainilla Cold Brew - Equilibrado",
        categoria: "cold brew",
        precio: 19.95,
        cantidad: "10 sobres",
        descripcion: "Cremoso y suave a la perfección, con un toque de dulzura que levanta tu café de todos los días. Pensado para preparar sin esfuerzo — caliente o con hielo — es un clásico reconfortante con un giro moderno.",
        sabor: "Madagascar Vainilla",
        origen: "Nicaragua",
        intensidad: "Equilibrado",
        fecha: "2024-07-01",
        imagen: "img/cafe-frio/vainillablend-medium.png",
        imagenes: [
            "img/cafe-frio/vainillablend-medium.png",
            "img/cafe-frio/vainillablend-medium-2.png",
            "img/cafe-frio/vainillablend-medium-3.png",
        ]
    },
    {
        id: 8,
        nombre: "Social Dog Cold Brew - Equilibrado",
        categoria: "cold brew",
        precio: 19.95,
        cantidad: "10 sobres",
        descripcion: "Equilibrado, suave y fácil de tomar sin pensarlo — nuestro blend orgánico de tueste medio de formato individual es ese café comodín para los momentos de todos los días. Con notas acogedoras de chocolate con leche y maní tostado, es amigable, accesible y... imposible no quererlo.",
        sabor: "Chocolate, maní y galletitas.",
        origen: "Perú, Nicaragua",
        intensidad: "Equilibrado",
        fecha: "2024-07-01",
        imagen: "img/cafe-frio/socialdog-medium.png",
        imagenes: [
            "img/cafe-frio/socialdog-medium.png",
            "img/cafe-frio/socialdog-medium-2.png",
            "img/cafe-frio/socialdog-medium-3.png",
        ]
    },
    {
        id: 9,
        nombre: "Variados Saborizados Cold Brew",
        categoria: "cold brew",
        precio: 19.95,
        cantidad: "10 sobres",
        descripcion: "Descubrí una selección especial de nuestros blends saborizados más icónicos, en un formato individual pensado para disfrutar tanto caliente como con hielo. Intenso, equilibrado y súper versátil, este pack variado le da un toque refinado a tu ritual cafetero de todos los días.",
        sabor: "Variado",
        origen: "Arabica",
        intensidad: "Ligero, Equilibrado, Intenso",
        fecha: "2024-10-05",
        imagen: "img/cafe-frio/flavored-variety.png",
        imagenes: [
            "img/cafe-frio/flavored-variety.png",
            "img/cafe-frio/flavored-variety-2.png",
            "img/cafe-frio/flavored-variety-3.png",
        ]
    },
    {
        id: 10,
        nombre: "Cold Brew - Starter Pack",
        categoria: "cold brew",
        precio: 49.45,
        cantidad: "10 sobres, 2 sorbitos, 1 vaso",
        descripcion: "Todo lo que necesitás para arrancar tu ritual de cold brew, desde sobres individuales de café hasta nuestro icónico frasco estilo mason jar para prepararlo fácil en casa. Todo el sabor de un cold brew delicioso, sin el menor esfuerzo. Incluye: sobres individuales surtidos, frasco mason jar y set de pajitas de acero inoxidable.",
        sabor: "Variado",
        origen: "Arabica",
        intensidad: "Ligero, Equilibrado, Intenso",
        fecha: "2024-10-05",
        imagen: "img/cafe-frio/starter-pack.png",
        imagenes: [
            "img/cafe-frio/starter-pack.png",
            "img/cafe-frio/starter-pack-2.png",
            "img/cafe-frio/starter-pack-3.png",
        ]
    },
    {
        id: 11,
        nombre: "Té Matcha Orgánico",
        categoria: "matcha",
        precio: 29.95,
        cantidad: "30g",
        descripcion: "Vibrante, suave y molido a la perfección, nuestro matcha orgánico grado ceremonial está hecho con té verde japonés premium para darte un impulso limpio y lleno de buena energía. Con un sabor naturalmente dulce y terroso, sin nada de amargor, se convierte en tu nuevo favorito para activar con calma y enfoque.",
        sabor: "Herbal y ligeramente amargo",
        origen: "Shizuoka, Japón",
        intensidad: "Grado Ceremonial A",
        fecha: "2025-02-04",
        imagen: "img/matcha/matcha.png",
        imagenes: [
            "img/matcha/matcha.png",
            "img/matcha/matcha-2.png",
            "img/matcha/matcha-3.png",
        ]
    },
    {
        id: 12,
        nombre: "Té Matcha sabor Vainilla",
        categoria: "matcha",
        precio: 29.95,
        cantidad: "30g",
        descripcion: "Una vuelta suave y sutilmente dulce de nuestro matcha clásico, infusionado con un toque de vainilla cálida para un sorbo acogedor y reconfortante. Terroso, cremoso y con el sabor justo para sumarle algo especial a tu ritual de todos los días.",
        sabor: "Vainilla",
        origen: "Shizuoka, Japón",
        intensidad: "Grado Ceremonial A",
        fecha: "2025-02-04",
        imagen: "img/matcha/matcha-vainilla.png",
        imagenes: [
            "img/matcha/matcha-vainilla.png",
            "img/matcha/matcha-vainilla-2.png",
            "img/matcha/matcha-vainilla-3.png",
        ]
    },
    {
        id: 13,
        nombre: "Té Matcha sabor Chocolate",
        categoria: "matcha",
        precio: 29.95,
        cantidad: "30g",
        descripcion: "Chocolate y matcha se unen en un blend con el toque justo de intensidad. Es una vuelta reconfortante a tu matcha de todos los días, con ese gustito que da ganas de repetir.",
        sabor: "Chocolate",
        origen: "Shizuoka, Japón",
        intensidad: "Grado Ceremonial A",
        fecha: "2025-02-04",
        imagen: "img/matcha/matcha-chocolate.png",
        imagenes: [
            "img/matcha/matcha-chocolate.png",
            "img/matcha/matcha-chocolate-2.png",
            "img/matcha/matcha-chocolate-3.png",
        ]
    },
    {
        id: 14,
        nombre: "Té Matcha sabor Durazno",
        categoria: "matcha",
        precio: 29.95,
        cantidad: "30g",
        descripcion: "Nuestro té Matcha sabor Durazno combina matcha grado ceremonial A con notas de durazno maduro y jugoso para una mezcla frutal con dulzura sutil. Perfecto para tomar caliente o con hielo, sin necesidad de endulzantes.",
        sabor: "Durazno",
        origen: "Shizuoka, Japón",
        intensidad: "Grado Ceremonial A",
        fecha: "2025-02-04",
        imagen: "img/matcha/matcha-durazno.png",
        imagenes: [
            "img/matcha/matcha-durazno.png",
            "img/matcha/matcha-durazno-2.png",
            "img/matcha/matcha-durazno-3.png",
        ]
    }
]